# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d41fed2d431f0372771d1ded4bab654ef28e9f884a4d6ee5afc08dcac0ca97cfa4377391f0d06efae2fae1ac345e20b3d0fd56991317205a416c29563bdfe9cc

test:
  secret_key_base: 0e35dd2cb24343d6ebc2feb81e638df36ed25be32f0b5f25d333100ee7b00f8615b4e55aed0005675a9dd2ba8fc0813765badc9b3bbc7e165af9106b402bd0fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
